/* Datos por defecto — se usan solo la primera vez que se crea la fila en Supabase.
   A partir de ahí, la fuente de verdad es la base de datos. */

export const defaultData = {
  niveles: [
    { nivel: 'Civil ilegal', miembros: 'Individual (sin banda)', requisito: 'Punto de partida — nadie más', desbloquea: 'Clase E y D libres, sin banda. Clase C ya no es para civiles sueltos, hace falta PDB', limite: 'Sin tope fijo en E y D (a definir si hace falta)' },
    { nivel: 'PDB', miembros: '5 oficiales (0 outsiders)', requisito: 'Mínimo 5 civiles ilegales se organizan', desbloquea: 'Clase C + 1 Ammu-Nation/semana (no clase B en general, solo ese objetivo)', limite: 'Hasta 3 clase C/día + 1 Ammu-Nation/semana' },
    { nivel: 'Banda Nivel 1 (Oficial)', miembros: '7 oficiales (+2 outsiders)', requisito: '3 casas en 1 barrio, pagadas con Dinero negro blanqueado a través del negocio legal propio de la banda + misión de la Mafia Administrativa', desbloquea: 'Clase B completo (todos los objetivos, no solo Ammu-Nation). Clase E, D y C sin límite', limite: 'Hasta 4 clase B/semana' },
    { nivel: 'Banda Nivel 2', miembros: '8 oficiales (+3 outsiders)', requisito: '3 casas más (blanqueadas) en un 2º barrio + misión', desbloquea: 'Clase A y Clase S', limite: 'Hasta 6 clase B, 2 clase A, 1 clase S/semana' },
    { nivel: 'Banda Nivel 3', miembros: '10 oficiales (+10 outsiders)', requisito: '3 casas más (blanqueadas) en un 3er barrio + misión', desbloquea: 'Clase S+', limite: 'Hasta 8 clase B, 4 clase A, 2 clase S, 1 clase S+/mes' },
  ],
  reglasClase: [
    { clase: 'E', atracadores: 'Depende del robo (ver tabla)', policia: '0', patrullas: '0', bloqueos: 'No', armas: 'Ninguna', rehenes: '—', civil: 'Sí' },
    { clase: 'D', atracadores: 'Máx. 2', policia: '0', patrullas: '1', bloqueos: 'No', armas: 'Blancas', rehenes: '—', civil: 'Sí' },
    { clase: 'C', atracadores: 'Máx. 3', policia: '6', patrullas: '3', bloqueos: 'No', armas: 'Blancas', rehenes: 'Hasta 2', civil: 'No' },
    { clase: 'B', atracadores: 'Máx. 4', policia: '8', patrullas: '4', bloqueos: 'Sí', armas: 'Fuego', rehenes: 'Hasta 8', civil: 'No' },
    { clase: 'A', atracadores: 'Máx. 6', policia: '12', patrullas: '6', bloqueos: 'Sí', armas: 'Fuego', rehenes: 'Hasta 10', civil: 'No' },
    { clase: 'S', atracadores: 'Máx. 8', policia: '16', patrullas: '8', bloqueos: 'Sí', armas: 'Fuego', rehenes: '—', civil: 'No' },
    { clase: 'S+', atracadores: 'Máx. 10', policia: '20', patrullas: '10', bloqueos: 'Sí', armas: 'Fuego', rehenes: '—', civil: 'No' },
  ],
  robos: [
    { clase: 'E', robo: 'Madera', requiere: 'Hacha (comprable, sin daño)', da: 'Madera x3', atracadores: 'Sin límite' },
    { clase: 'E', robo: 'Plantación de droga', requiere: 'Semillas', da: 'Droga cruda x2', atracadores: 'Sin límite' },
    { clase: 'E', robo: 'Tumbas', requiere: 'Pala (comprable, sin daño)', da: 'Reloj x1 + material aleatorio x1 + Dinero negro $80', atracadores: 'Sin límite' },
    { clase: 'E', robo: 'Robo de coches de importación', requiere: 'Nada — NPC da ubicación, buscas llave, entregas en otro punto', da: 'Dinero negro $150', atracadores: 'Máx. 1' },
    { clase: 'E', robo: 'Contenedor industrial pequeño', requiere: 'Palanca', da: 'Chatarra x2 + Alambre rígido x1 + Mercancía variada x1', atracadores: 'Máx. 3' },
    { clase: 'D', robo: 'ATM', requiere: 'Cuerda con gancho + coche con maletero', da: 'Dinero negro $250', atracadores: 'Máx. 2' },
    { clase: 'D', robo: 'Tienda de tatuajes', requiere: 'Ganzúa', da: 'Dinero negro $200 + Tinta x1', atracadores: 'Máx. 2' },
    { clase: 'D', robo: 'Peluquería', requiere: 'Ganzúa', da: 'Dinero negro $200', atracadores: 'Máx. 2' },
    { clase: 'D', robo: 'Licorería', requiere: 'Ganzúa', da: 'Dinero negro $200 + Alcohol x2', atracadores: 'Máx. 2' },
    { clase: 'D', robo: 'Tienda de ropa', requiere: 'Nada', da: 'Dinero negro $200 + Prendas x2', atracadores: 'Máx. 2' },
    { clase: 'D', robo: 'Robo a casas', requiere: 'Nada — casas random del mapa, sin /robos', da: 'Reloj x1 + Joyas x1 + Cobre x1 + Dinero negro $120', atracadores: 'Sin límite' },
    { clase: 'D', robo: 'Farmacia (robo rápido)', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 2' },
    { clase: 'C', robo: 'LTD (Badulaque)', requiere: 'Ganzúa avanzada', da: 'Dinero negro $500 + Cinta aislante x1', atracadores: 'Máx. 3' },
    { clase: 'C', robo: 'Desguace', requiere: 'Cizalla', da: 'Hierro x2 + Cobre x2 + Caucho x2 + Metal x2 + Piezas de coche x1', atracadores: 'Máx. 3' },
    { clase: 'C', robo: 'Contenedor industrial grande', requiere: 'Decodificador industrial', da: 'Placas electrónicas x1 + Cobre x2', atracadores: 'Máx. 3' },
    { clase: 'C', robo: 'Furgón de reparto de mercancía', requiere: 'Dispositivo de pinchos', da: 'Placas electrónicas x1 + Mercancía variada x2', atracadores: 'Máx. 3' },
    { clase: 'B', robo: 'Ammu-Nation', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 4' },
    { clase: 'B', robo: 'Joyería (Vangelico)', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 4' },
    { clase: 'B', robo: 'Fleeca (6 sucursales)', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 4' },
    { clase: 'B', robo: 'Pawnshop', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 4' },
    { clase: 'B', robo: 'Farmacia (heist grande)', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 4' },
    { clase: 'B', robo: 'Furgón blindado pequeño', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 4' },
    { clase: 'A', robo: 'Banco Paleto', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 6' },
    { clase: 'A', robo: 'Union Depository', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 6' },
    { clase: 'A', robo: 'Furgón blindado grande', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 6' },
    { clase: 'A', robo: 'Tren de mercancías', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 6' },
    { clase: 'S', robo: 'Yate', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 8' },
    { clase: 'S', robo: 'Diamond Casino', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 8' },
    { clase: 'S', robo: 'Humane Labs', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 8' },
    { clase: 'S', robo: 'Avión de carga', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 8' },
    { clase: 'S+', robo: 'Banco Central', requiere: 'Pendiente', da: 'Pendiente', atracadores: 'Máx. 10' },
  ],
  materiales: [
    { material: 'Madera', fuente: 'Robo de Madera (D)', uso: 'Crafteo (Mango), venta' },
    { material: 'Droga cruda', fuente: 'Plantación de droga (E)', uso: 'Crafteo (Bolsa de droga) — ya no se vende directa' },
    { material: 'Bolsa de droga', fuente: 'Crafteo con Droga cruda en la mesa de ensamblaje básica', uso: 'Venteo callejero (ver nota) o venta a perista' },
    { material: 'Reloj / Material aleatorio', fuente: 'Tumbas (E), Robo a casas (D)', uso: 'Venta a perista' },
    { material: 'Joyas', fuente: 'Robo a casas (D)', uso: 'Venta a perista' },
    { material: 'Dinero negro', fuente: 'Tumbas, ATM, tatuajes, pelu, licorería, coches de importación, casas, LTD, tienda de ropa', uso: 'Economía directa' },
    { material: 'Tinta', fuente: 'Tienda de tatuajes (D)', uso: 'Crafteo (Bote de grafiti, Pasamontañas), venta' },
    { material: 'Alcohol', fuente: 'Licorería (D)', uso: 'Crafteo (Cóctel molotov), venta' },
    { material: 'Chatarra', fuente: 'Contenedor pequeño (E) + farmeo en puntos de chatarra del mapa (ver nota)', uso: 'Crafteo básico' },
    { material: 'Alambre rígido', fuente: 'Contenedor pequeño (E) + farmeo en puntos de chatarra del mapa', uso: 'Crafteo (Ganzúa)' },
    { material: 'Cinta aislante', fuente: 'LTD (C) + farmeo en puntos de chatarra del mapa', uso: 'Crafteo (Ganzúa)' },
    { material: 'Cobre', fuente: 'Contenedor grande (C), Desguace (C), Robo a casas (D)', uso: 'Crafteo (Cable de cobre)' },
    { material: 'Hierro', fuente: 'Desguace (C) + farmeo en puntos de chatarra del mapa', uso: 'Crafteo (Navaja, Bate)' },
    { material: 'Caucho', fuente: 'Desguace (C) + farmeo en puntos de chatarra del mapa', uso: 'Crafteo (Mango)' },
    { material: 'Metal', fuente: 'Desguace (C) + farmeo en puntos de chatarra del mapa', uso: 'Crafteo (Ganzúa avanzada, Palanca, Cizalla, Pinchos)' },
    { material: 'Piezas de coche', fuente: 'Desguace (C)', uso: 'Crafteo (Dispositivo de pinchos), venta' },
    { material: 'Placas electrónicas', fuente: 'Contenedor grande (C), Furgón de reparto (C)', uso: 'Crafteo (Decodificador industrial)' },
    { material: 'Mercancía variada', fuente: 'Contenedor pequeño (E), Furgón de reparto (C)', uso: 'Venta (no crafteo)' },
    { material: 'Prendas', fuente: 'Tienda de ropa (D)', uso: 'Crafteo (Pasamontañas), venta' },
    { material: 'Semillas', fuente: 'Comprables en GrowShop y se pueden conseguir en otros lugares', uso: 'Requisito para Plantación de droga' },
  ],
  crafteo: [
    { objeto: 'Mango', mesa: 'Refinado', receta: 'Madera x1 + Caucho x1', uso: 'Componente para herramientas y armas blancas' },
    { objeto: 'Cable de cobre', mesa: 'Refinado', receta: 'Cobre x2', uso: 'Decodificador industrial' },
    { objeto: 'Navaja casera', mesa: 'Ensamblaje básica', receta: 'Hierro x1 + Mango x1', uso: 'Arma blanca' },
    { objeto: 'Bate de béisbol', mesa: 'Ensamblaje básica', receta: 'Madera x1', uso: 'Arma blanca' },
    { objeto: 'Bate con clavos', mesa: 'Ensamblaje básica', receta: 'Madera x1 + Hierro x1', uso: 'Arma blanca' },
    { objeto: 'Machete', mesa: 'Ensamblaje básica', receta: 'Hierro x2 + Mango x1', uso: 'Arma blanca' },
    { objeto: 'Martillo', mesa: 'Ensamblaje básica', receta: 'Metal x1 + Mango x1', uso: 'Arma blanca' },
    { objeto: 'Llave inglesa', mesa: 'Ensamblaje básica', receta: 'Metal x1', uso: 'Arma blanca' },
    { objeto: 'Hacha de combate', mesa: 'Ensamblaje básica', receta: 'Hierro x1 + Madera x1', uso: 'Arma blanca (distinta del Hacha herramienta, que no hace daño)' },
    { objeto: 'Nudilleras', mesa: 'Ensamblaje básica', receta: 'Metal x1', uso: 'Arma blanca' },
    { objeto: 'Porra improvisada', mesa: 'Ensamblaje básica', receta: 'Chatarra x1 + Caucho x1', uso: 'Arma blanca' },
    { objeto: 'Ganzúa', mesa: 'Ensamblaje básica', receta: 'Alambre rígido x1 + Cinta aislante x1', uso: 'Robos D + coches' },
    { objeto: 'Bolsa de droga', mesa: 'Ensamblaje básica', receta: 'Droga cruda x2', uso: 'Producto final de venta — venteo callejero o perista' },
    { objeto: 'Ganzúa avanzada', mesa: 'Ensamblaje avanzada', receta: 'Ganzúa x1 + Metal x2 + Cable de cobre x1', uso: 'Robos clase C en adelante' },
    { objeto: 'Palanca', mesa: 'Ensamblaje básica', receta: 'Metal x1 + Mango x1', uso: 'Contenedor industrial pequeño' },
    { objeto: 'Cizalla', mesa: 'Ensamblaje avanzada', receta: 'Metal x2 + Mango x1', uso: 'Desguace' },
    { objeto: 'Dispositivo de pinchos', mesa: 'Ensamblaje avanzada', receta: 'Piezas de coche x1 + Metal x1', uso: 'Furgón de reparto' },
    { objeto: 'Cóctel molotov', mesa: 'Ensamblaje básica', receta: 'Alcohol x2 + Chatarra x1', uso: 'Arma incendiaria improvisada' },
    { objeto: 'Pasamontañas', mesa: 'Ensamblaje básica', receta: 'Prendas x1 + Tinta x1', uso: 'Reduce reconocimiento durante un robo' },
    { objeto: 'Bote de grafiti', mesa: 'Ensamblaje básica', receta: 'Tinta x1 + Chatarra x1', uso: 'Marcar territorio de la banda' },
    { objeto: 'Cuerda con gancho', mesa: 'Ensamblaje básica', receta: 'Metal x1', uso: 'ATM' },
    { objeto: 'Decodificador industrial', mesa: 'Ensamblaje avanzada', receta: 'Placas electrónicas x2 + Cable de cobre x2', uso: 'Contenedor industrial grande' },
  ],
  mesas: [
    { mesa: 'Mesa de refinado', acceso: 'Pública — cualquier civil ilegal, sin banda', que: 'Convierte materiales en bruto en componentes (ej. Cobre → Cable de cobre)', porque: 'Es el primer paso, no puede tener restricción o nadie podría ni empezar' },
    { mesa: 'Mesa de ensamblaje básica', acceso: 'Pública — cualquier civil ilegal, sin banda', que: 'Monta Ganzúa, Cuerda con gancho, Palanca, Navaja casera, Bate, Mango, Bolsa de droga, herramientas D/C', porque: 'Un civil ilegal solo debe poder craftear lo mínimo para su primer robo clase D, y también empaquetar la droga cruda que ha plantado él mismo' },
    { mesa: 'Mesa de ensamblaje avanzada', acceso: 'Privada — dentro de una casa propiedad de la banda, Nivel 1+', que: 'Monta Ganzúa avanzada, Cizalla, Dispositivo de pinchos, Decodificador industrial y las armas blancas más serias', porque: 'Ata el mejor equipo a tener territorio real, no solo a comprar materiales' },
  ],
  npcs: [
    { npc: 'Perista / Fence', cuantos: '2-3', ubicacion: 'Puntos fijos discretos repartidos por el mapa (callejones, descampados)', para: 'Vender Dinero negro, materiales y objetos robados sin pasar por tiendas legales', porque: 'Más de uno evita cuellos de botella si hay varias bandas activas a la vez, pero pocos para que siga siendo un punto de encuentro reconocible' },
    { npc: 'Proveedor de piezas raras', cuantos: '1', ubicacion: 'Ubicación fija, poco conocida', para: 'Vender materiales difíciles de conseguir por robo (ej. Placas electrónicas sueltas) a precio alto', porque: 'Debe ser un cuello de botella real, si hay varios pierde sentido como vía alternativa cara' },
    { npc: 'Mafia Administrativa', cuantos: 'No es un NPC fijo, es la misión de subida de nivel', ubicacion: 'Se activa al cumplir el requisito de casas del nivel', para: 'Dar la misión que junto con las casas blanqueadas permite subir de nivel de banda', porque: 'No tiene sentido como NPC físico, es un evento/misión gestionado' },
    { npc: 'Vendedor de ganzúas', cuantos: '1-2', ubicacion: 'Punto fijo discreto, a definir', para: 'Vende Ganzúa y Ganzúa avanzada ya montadas, sin tener que craftearlas', porque: 'Son herramientas que hace falta tener siempre a mano; vía alternativa más cómoda pero pensada para costar más que craftearla tú mismo — no sustituye el resto de lo que da el territorio en Nivel 1+' },
    { npc: 'Informante de bandas', cuantos: '1', ubicacion: 'Cerca de donde se reúnen los civiles ilegales', para: 'Explica por diálogo la escalera de niveles: qué hace falta para fundar PDB, qué piden las casas y la misión, qué desbloquea cada nivel', porque: 'Un civil ilegal nuevo necesita enterarse del sistema jugando, sin depender de leer la normativa entera' },
    { npc: 'Encargado de las mesas', cuantos: '1', ubicacion: 'Junto a la mesa de refinado / ensamblaje básica', para: 'Explica por diálogo el crafteo en dos pasos: primero refinar materiales, luego ensamblar el objeto', porque: 'Las mesas por sí solas no explican el proceso, hace falta un punto de info antes de tocar el menú' },
    { npc: 'Contacto de robos', cuantos: '1-2', ubicacion: 'Puntos conocidos cerca de zonas con robos clase D/C', para: 'Explica por diálogo las clases de robo, qué hace falta para cada una y qué puedes sacar', porque: 'Sirve de tutorial dentro del propio mapa, en vez de depender de leer el catálogo entero' },
    { npc: 'Chatarrero', cuantos: '1', ubicacion: 'Cerca del Desguace', para: 'Trueque, no venta: le das Mercancía variada o Piezas de coche sueltas y te da Metal o Hierro a cambio', porque: 'Hoy esos dos materiales solo se pueden vender; así tienen una segunda utilidad real sin tocar las recetas de las mesas' },
    { npc: 'Comprador de coches (Desguace)', cuantos: '1', ubicacion: 'En el propio Desguace, aparte del robo al Desguace', para: 'Le entregas cualquier coche robado por la calle (no el de importación, ese va a otro punto) y te da Piezas de coche x1 + Dinero negro $100. El coche se destruye', porque: 'El robo al Desguace es un golpe puntual con Cizalla; esto le da salida a robar coches sueltos del día a día, sin límite ni cooldown' },
  ],
  licencias: [
    { paso: '1. Psicotécnico', quien: 'EMS', requisito: 'Pasar la prueba psicotécnica con un miembro EMS', coste: 'A definir', notas: 'Sin esto no se puede pedir la licencia de armas' },
    { paso: '2. Licencia de armas', quien: 'LSSD', requisito: 'Psicotécnico EMS aprobado', coste: 'A definir', notas: 'La expide LSSD, no cualquier agente' },
    { paso: '3. Compra de la pistola', quien: 'Persona administrativa de Ammu-Nation', requisito: 'Licencia de armas en regla', coste: '$3.000', notas: 'Solo defensa personal. La policía puede retirar licencia y pistola si se usa de forma no justificada' },
  ],
  notas: {
    n01: 'Empiezas como <b>civil ilegal</b>, solo, sin banda: puedes hacer robos clase D libremente y algo de clase C con tope semanal. Para craftear lo básico (ganzúa, armas blancas simples) usas las <b>mesas públicas</b> — no hace falta banda ni territorio para eso. Cuando 5 civiles ilegales se organizan forman una <b>PDB</b>, el primer escalón de banda: todavía sin privilegios nuevos, es la fase de ahorrar. Comprando <b>3 casas en un barrio</b> con <b>Dinero negro ya blanqueado</b> (a través del único negocio legal que puede tener la banda) y completando la misión que asigna la Mafia Administrativa, la banda asciende a <b>Nivel 1</b> y desbloquea robos clase B completos. Repitiendo eso en un segundo y tercer barrio se llega a Nivel 2 (clase A y S) y Nivel 3 (clase S+). Cuanto más sube la banda, más mesas y equipo avanzado tiene disponible dentro de su propio territorio.',
    n02: 'Todos empiezan como <b>civil ilegal</b>: clase D libre, clase C con tope semanal (editable en la pestaña Robos). Al organizarse mínimo 5, forman un <b>PDB</b> — sin privilegios nuevos, es la fase de ahorrar para comprar territorio. Cada ascenso de nivel exige <b>dos cosas a la vez</b>: el número de casas indicado Y completar la misión que asigna la Mafia Administrativa (misión libre, no hay catálogo cerrado — ejemplo de misión: transportar un cargamento de un punto A a un punto B en coche, con riesgo de que la policía lo intercepte por el camino).',
    n03: '<b>Antes de poder fundar un PDB:</b> los 5 civiles ilegales que se juntan deben tener cada uno un mínimo de robos clase D/C completados a su nombre — así fundar banda es algo que se gana jugando, no un trámite de juntar 5 nombres el primer día. Número exacto de robos: a definir.',
    n04: '<b>Tamaño de barrios:</b> depende de la zona — no todos tienen el mismo número de casas, sigue la lógica de cada sitio del mapa.<br><b>Disputas por el mismo barrio:</b> no hay bloqueo exclusivo por script. Si una banda ya está consolidada en un territorio, puede echar a otras por rol. Si dos bandas se lo disputan activamente, se resuelve a nivel de rol, como las partes quieran. No es una regla automática del sistema, es narrativo.',
    n05: '<b>Blanqueo (por qué las casas ya no se compran "a pelo"):</b> la normativa de Comercios ya dice que una banda puede tener <b>1 único negocio legal propio</b>, con vigilancia especial anti-blanqueo. Las 3 casas de cada ascenso de nivel se pagan con Dinero negro que primero tiene que pasar por ese negocio — comprar territorio con dinero sin blanquear no cuenta. Esto hace que el ascenso dependa de tener una operación de blanqueo funcionando de verdad, no solo de tener ahorros.',
    n06: '<b>Servicio de seguridad armada:</b> la normativa de Comercios permite a un negocio contratar "una banda externa como servicio de protección pagado" — con permiso para ir armados. Es un ingreso legítimo para la banda (a partir de Nivel 1, cuando ya tiene acceso a clase B y por tanto a armamento serio), sin que sea extorsión — el negocio contrata voluntariamente.',
    n07: '<b>Ruptura de negociaciones:</b> cuando falla la negociación obligatoria de un robo clase B en adelante, no hace falta una regla nueva — se activa el mismo protocolo de "Ruptura de Negociaciones" que ya usa la policía para persecuciones (los 11 supuestos: abrir fuego, cambiar de vehículo, bloqueos, etc.), con la Clave ROBERT como último recurso de fuerza letal.',
    n08: 'Pendiente ampliar a clase B en adelante — de momento solo lo necesario para D y C.',
    n09: '<b>Puntos de chatarra:</b> Chatarra, Alambre rígido, Cinta aislante, Hierro, Caucho y Metal también se consiguen recogiéndolos en puntos fijos repartidos por el mapa (descampados, vertederos, garajes), sin robar nada. Dan x1 por recogida, con 10-15 minutos de cooldown por punto — la mitad o menos de lo que da el robo correspondiente, así que el robo sigue siendo la vía rápida y rentable, y esto queda como alternativa lenta para quien todavía no puede o no quiere robar.<br><br>Con esto, un civil ilegal solo, sin banda, puede craftear su primera Ganzúa (antes la Cinta aislante solo salía de LTD, un robo de clase C) y las bandas pueden hacer su primer Desguace sin depender de tener ya el Metal que solo daba el propio Desguace.',
    n10: 'En vez de una mesa única que hace de todo, el crafteo va en dos pasos. Esto da más profundidad y además resuelve un problema: si todo el ensamblaje estuviera solo dentro de territorio de banda, un civil ilegal sin banda no podría ni hacer su primera ganzúa — por eso el refinado y el ensamblaje básico son públicos, y solo el ensamblaje avanzado exige territorio.',
    n11: 'Esto es la compra <b>legal</b> de un arma — no confundir con el Ammu-Nation que aparece en el catálogo de robos (clase B), que es el mismo edificio pero como objetivo a robar. Aquí un civil consigue su propia pistola siguiendo el proceso, sin necesidad de banda ni territorio.',
    n12: '<b>Clase E:</b> sin /robos, se hacen directamente en el mapa. Necesitan mínimo 1 policía de servicio conectado para poder hacerse, si no, no dejan. Sin límite, se pueden hacer 24/7. Dan poca pasta y algún material.',
    n13: '<b>Por qué esas cantidades:</b> E da lo mínimo porque es sin límite y se puede repetir 24/7 (dinero negro entre $80 y $150, materiales x1-x3). D da algo más del doble que E porque hace falta organizarse un poco más y hay tope de 2 atracadores (dinero negro $200-250). C da el doble de D porque ya es solo para PDB, con más riesgo y más policía (dinero negro $500, materiales x1-x2 pero de los que hacen falta para el equipo avanzado). Desguace da más variedad de materiales de golpe (5 tipos) porque es el único sitio que surte a Metal, Caucho e Hierro a la vez — un solo golpe bueno compensa el riesgo de hacerlo en C. Las cantidades de las recetas de crafteo (Mesas y NPCs → ver Crafteo) ya están pensadas para que un par de golpes del robo correspondiente basten para un objeto normal, y algunos más para los avanzados (Ganzúa avanzada, Decodificador industrial).',
    n14: '<b>Venteo callejero:</b> la Droga cruda no se vende directa, primero hay que craftearla. Se planta con Semillas (Plantación de droga, clase E), y esa Droga cruda se lleva a la mesa de ensamblaje básica para convertirla en Bolsa de droga (Droga cruda x2 por bolsa). Es la bolsa la que se vende: en vez de entregarla entera a un perista de una vez, se va gastando de una en una vendiendo a NPCs random por la calle — cada bolsa da Dinero negro entre $30 y $60. Riesgo: hay una probabilidad de que el NPC sea policía de paisano, así que no es zona 100% segura. Es la fuente de ingreso para quien no tiene banda ni territorio: lento pero constante, sin depender de organizar nada.',
    n15: '<b>Mercado negro entre bandas:</b> cuando una banda tiene de sobra un material y necesita otro, no hace falta que las dos bandas se vean cara a cara (riesgo de emboscada). Se usa al Perista como intermediario: una banda le deja el material en depósito pidiendo lo que quiere a cambio, y la otra banda interesada trae lo pedido a ese mismo Perista para cerrar el trato ahí. El Perista se queda una pequeña comisión en Dinero negro por hacer de intermediario neutral.',
  },
  estatico: {
    'brand-title': 'Proyecto <span>S</span> · Facción Ilegal',
    'brand-tagline': 'Siega Community — herramienta de trabajo, editable. Los cambios se guardan en la nube y los ve todo el equipo en tiempo real.',
    'tab-niveles': 'Niveles de Banda',
    'tab-robos': 'Robos por Clase',
    'tab-materiales': 'Materiales',
    'tab-crafteo': 'Crafteo',
    'tab-mesas': 'Mesas y NPCs',
    'tab-licencias': 'Ammu-Nation legal',
    sh1: 'Resumen — cómo funciona todo el sistema',
    sh2: 'Territorio',
    sh3: 'Economía legal de la banda',
    hint3: 'Cruzado con la normativa de Comercios ya existente',
    sh4: 'Tabla editable de niveles',
    hint4: 'Click en cualquier celda para editar',
    sh5: 'Reglas por clase',
    hint5: 'Base para todos los robos de esa clase',
    sh6: 'Catálogo de robos',
    hint6: 'Detalle completo hasta clase C — B/A/S/S+ solo nombres por ahora',
    sh7: 'Materiales (D y C)',
    hint7: 'Qué es, de dónde sale, para qué sirve',
    sh8: 'Componentes y herramientas',
    hint8: 'Receta de cada objeto craftable',
    sh9: 'Mesas de crafteo',
    hint9: 'El proceso va en 2 pasos: refinar materiales, luego ensamblar',
    sh10: 'NPCs',
    hint10: 'Cuántos, dónde y para qué',
    sh11: 'Ammu-Nation legal — compra de pistola con licencia',
    hint11: 'Sistema civil, sin relación con las bandas',
    footer: 'Proyecto S — Siega Community · documento de trabajo interno, no compartir fuera del equipo.',
    'th-tbl-niveles-0': 'Nivel', 'th-tbl-niveles-1': 'Miembros', 'th-tbl-niveles-2': 'Requisito de ascenso', 'th-tbl-niveles-3': 'Desbloquea', 'th-tbl-niveles-4': 'Límite semanal de robos',
    'th-tbl-reglasClase-0': 'Clase', 'th-tbl-reglasClase-1': 'Atracadores', 'th-tbl-reglasClase-2': 'Policía mín.', 'th-tbl-reglasClase-3': 'Patrullas', 'th-tbl-reglasClase-4': 'Bloqueos', 'th-tbl-reglasClase-5': 'Armas', 'th-tbl-reglasClase-6': 'Rehenes', 'th-tbl-reglasClase-7': 'Civil ilegal',
    'th-tbl-robos-0': 'Clase', 'th-tbl-robos-1': 'Robo', 'th-tbl-robos-2': 'Requiere', 'th-tbl-robos-3': 'Da', 'th-tbl-robos-4': 'Atracadores',
    'th-tbl-materiales-0': 'Material', 'th-tbl-materiales-1': 'De dónde sale', 'th-tbl-materiales-2': 'Para qué sirve',
    'th-tbl-crafteo-0': 'Objeto', 'th-tbl-crafteo-1': 'Mesa', 'th-tbl-crafteo-2': 'Receta', 'th-tbl-crafteo-3': 'Para qué se usa',
    'th-tbl-mesas-0': 'Mesa', 'th-tbl-mesas-1': 'Acceso', 'th-tbl-mesas-2': 'Qué se hace ahí', 'th-tbl-mesas-3': 'Por qué',
    'th-tbl-npcs-0': 'NPC', 'th-tbl-npcs-1': 'Cuántos', 'th-tbl-npcs-2': 'Ubicación', 'th-tbl-npcs-3': 'Para qué sirve', 'th-tbl-npcs-4': 'Por qué esa cantidad',
    'th-tbl-licencias-0': 'Paso', 'th-tbl-licencias-1': 'Quién lo expide', 'th-tbl-licencias-2': 'Requisito', 'th-tbl-licencias-3': 'Coste', 'th-tbl-licencias-4': 'Notas',
  },
};

export const TABLE_CONFIG = {
  niveles: {
    columns: [
      { key: 'nivel', label: 'Nivel', width: '16%' },
      { key: 'miembros', label: 'Miembros', width: '14%' },
      { key: 'requisito', label: 'Requisito de ascenso', width: '26%' },
      { key: 'desbloquea', label: 'Desbloquea', width: '22%' },
      { key: 'limite', label: 'Límite semanal de robos' },
    ],
    empty: { nivel: 'Nuevo nivel', miembros: '', requisito: '', desbloquea: '', limite: '' },
    addLabel: '+ Añadir nivel',
  },
  reglasClase: {
    columns: [
      { key: 'clase', label: 'Clase' },
      { key: 'atracadores', label: 'Atracadores' },
      { key: 'policia', label: 'Policía mín.' },
      { key: 'patrullas', label: 'Patrullas' },
      { key: 'bloqueos', label: 'Bloqueos' },
      { key: 'armas', label: 'Armas' },
      { key: 'rehenes', label: 'Rehenes' },
      { key: 'civil', label: 'Civil ilegal' },
    ],
    empty: { clase: '', atracadores: '', policia: '', patrullas: '', bloqueos: '', armas: '', rehenes: '', civil: '' },
    addLabel: '+ Añadir clase',
  },
  robos: {
    columns: [
      { key: 'clase', label: 'Clase', width: '8%' },
      { key: 'robo', label: 'Robo', width: '20%' },
      { key: 'requiere', label: 'Requiere', width: '26%' },
      { key: 'da', label: 'Da', width: '26%' },
      { key: 'atracadores', label: 'Atracadores', width: '14%' },
    ],
    empty: { clase: 'D', robo: 'Nuevo robo', requiere: '', da: '', atracadores: '' },
    badgeCol: 'clase',
    addLabel: '+ Añadir robo',
  },
  materiales: {
    columns: [
      { key: 'material', label: 'Material', width: '20%' },
      { key: 'fuente', label: 'De dónde sale', width: '40%' },
      { key: 'uso', label: 'Para qué sirve' },
    ],
    empty: { material: 'Nuevo material', fuente: '', uso: '' },
    addLabel: '+ Añadir material',
  },
  crafteo: {
    columns: [
      { key: 'objeto', label: 'Objeto', width: '20%' },
      { key: 'mesa', label: 'Mesa', width: '16%' },
      { key: 'receta', label: 'Receta', width: '38%' },
      { key: 'uso', label: 'Para qué se usa', width: '26%' },
    ],
    empty: { objeto: 'Nuevo objeto', mesa: 'Ensamblaje básica', receta: '', uso: '' },
    addLabel: '+ Añadir objeto',
  },
  mesas: {
    columns: [
      { key: 'mesa', label: 'Mesa', width: '22%' },
      { key: 'acceso', label: 'Acceso', width: '16%' },
      { key: 'que', label: 'Qué se hace ahí', width: '30%' },
      { key: 'porque', label: 'Por qué' },
    ],
    empty: { mesa: 'Nueva mesa', acceso: '', que: '', porque: '' },
    addLabel: '+ Añadir mesa',
  },
  npcs: {
    columns: [
      { key: 'npc', label: 'NPC', width: '20%' },
      { key: 'cuantos', label: 'Cuántos', width: '10%' },
      { key: 'ubicacion', label: 'Ubicación', width: '22%' },
      { key: 'para', label: 'Para qué sirve', width: '24%' },
      { key: 'porque', label: 'Por qué esa cantidad' },
    ],
    empty: { npc: 'Nuevo NPC', cuantos: '', ubicacion: '', para: '', porque: '' },
    addLabel: '+ Añadir NPC',
  },
  licencias: {
    columns: [
      { key: 'paso', label: 'Paso', width: '18%' },
      { key: 'quien', label: 'Quién lo expide', width: '20%' },
      { key: 'requisito', label: 'Requisito', width: '32%' },
      { key: 'coste', label: 'Coste', width: '16%' },
      { key: 'notas', label: 'Notas' },
    ],
    empty: { paso: 'Nuevo paso', quien: '', requisito: '', coste: '', notas: '' },
    addLabel: '+ Añadir paso',
  },
};
